const SCREEN_WIDTH = screen.width;
const HALF_SCREEN_WIDTH = SCREEN_WIDTH/2;
const QUARTER_SCREEN_WIDTH = SCREEN_WIDTH/4;
const EIGHTH_SCREEN_WIDTH = SCREEN_WIDTH/8;

const SCREEN_HEIGHT = screen.height;
const HALF_SCREEN_HEIGHT = SCREEN_HEIGHT/2;
const QUARTER_SCREEN_HEIGHT = SCREEN_HEIGHT/4;
const EIGHTH_SCREEN_HEIGHT = SCREEN_HEIGHT/8;

const UNIT_BOX_SIZE = SCREEN_WIDTH*0.25;
const MIRROR_LENGTH = UNIT_BOX_SIZE*2;
const UNIT_LASER_SIZE = SCREEN_WIDTH*0.05;
const WALL_ASPECT_RATIO = 1.0/20;
const LASER_ASPECT_RATIO = 1.0/5;
const LASER_ARC_RADIUS = UNIT_LASER_SIZE*1.5;
const LASER_ARC_MAX = -15.0/16*Math.PI;
const LASER_ARC_MIN = -1.0/16*Math.PI;
const OUTER_TARGET_SIZE = UNIT_BOX_SIZE/15;
const MIDDLE_TARGET_SIZE = OUTER_TARGET_SIZE/2;
const INNER_TARGET_SIZE = MIDDLE_TARGET_SIZE/2;

let angleToControl =Math.PI; 
let mostRecentFirstReflection;
let targetHit;
let numberOfBounces;
let uniqueHits = [];

